In [43]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [55]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [61]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10003    PREGO  BT10    100     60  z0019_2.csv 2025-04-24 13:40:13.260476
1  10004    SERRA  BT50    100    200  z0019_2.csv 2025-04-24 13:40:13.260476
2  10005  MACHADO  BT50    100    100  z0019_2.csv 2025-04-24 13:40:13.260476

In [58]:
con.execute("""
                CREATE TABLE IF NOT EXISTS bronze_produtos(
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao   TIMESTAMP,
            )
            """)

In [62]:
con.execute("INSERT INTO bronze_z0019 SELECT * FROM df")

In [63]:
resultado = con.execute(f"SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-04-24 13:40:01.836649
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-04-24 13:40:01.836649
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-04-24 13:40:01.836649
3  10003     PREGO  BT10   100    60  z0019_2.csv 2025-04-24 13:40:13.260476
4  10004     SERRA  BT50   100   200  z0019_2.csv 2025-04-24 13:40:13.260476
5  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-04-24 13:40:13.260476

In [56]:
#con.execute("DELETE FROM bronze_z0019")

In [47]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

CatalogException: Catalog Error: Could not rename "bronze_produtos" to "bronze_z0019": another entry with this name already exists!

In [64]:
con.close()